# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 233) do

  create_table "assets", :force => true do |t|
    t.column "project_id",       :integer
    t.column "parent_id",        :integer
    t.column "user_id",          :integer
    t.column "name",             :string
    t.column "content_type",     :string
    t.column "filename",         :string
    t.column "size",             :integer
    t.column "thumbnail",        :string
    t.column "width",            :integer
    t.column "height",           :integer
    t.column "thumbnails_count", :integer,                :default => 0
    t.column "lock_version",     :integer,                :default => 0,     :null => false
    t.column "created_by",       :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",       :datetime,                                  :null => false
    t.column "updated_by",       :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",       :datetime,                                  :null => false
    t.column "desciption",       :text
  end

  create_table "assigned_sections", :force => true do |t|
    t.column "article_id", :integer
    t.column "section_id", :integer
    t.column "position",   :integer, :default => 1
  end

  create_table "audit_logs", :force => true do |t|
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "user_id",        :integer
    t.column "action",         :string
    t.column "changes",        :text
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  create_table "audits", :force => true do |t|
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "user_id",        :integer
    t.column "user_type",      :string
    t.column "session",        :string
    t.column "action",         :string
    t.column "changes",        :text
    t.column "created_at",     :datetime
  end

  add_index "audits", ["auditable_id", "auditable_type"], :name => "auditable_index"
  add_index "audits", ["user_id", "user_type"], :name => "user_index"
  add_index "audits", ["created_at"], :name => "audits_created_at_index"

  create_table "authentication_systems", :force => true do |t|
    t.column "name",             :string,   :limit => 50, :default => "",            :null => false
    t.column "description",      :text
    t.column "type",             :string,                 :default => "DataConcept", :null => false
    t.column "host",             :string,   :limit => 60
    t.column "port",             :integer
    t.column "account",          :string,   :limit => 60
    t.column "account_password", :string,   :limit => 60
    t.column "base_dn",          :string
    t.column "attr_login",       :string,   :limit => 30
    t.column "attr_firstname",   :string,   :limit => 30
    t.column "attr_lastname",    :string,   :limit => 30
    t.column "attr_mail",        :string,   :limit => 30
    t.column "lock_version",     :integer,                :default => 0,             :null => false
    t.column "created_by",       :string,   :limit => 32, :default => "sys",         :null => false
    t.column "created_at",       :datetime,                                          :null => false
    t.column "updated_by",       :string,   :limit => 32, :default => "sys",         :null => false
    t.column "updated_at",       :datetime,                                          :null => false
  end

  create_table "batches", :force => true do |t|
    t.column "compound_id",    :integer,                :default => 0,     :null => false
    t.column "name",           :string
    t.column "description",    :text
    t.column "external_ref",   :string
    t.column "quantity_unit",  :string
    t.column "quantity_value", :float
    t.column "url",            :string
    t.column "lock_version",   :integer,                :default => 0,     :null => false
    t.column "created_by",     :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",     :datetime,                                  :null => false
    t.column "updated_by",     :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",     :datetime,                                  :null => false
  end

  add_index "batches", ["compound_id"], :name => "batches_compound_fk"

  create_table "cached_pages", :force => true do |t|
    t.column "url",        :string
    t.column "references", :text
    t.column "updated_at", :datetime
    t.column "project_id", :integer
    t.column "cleared_at", :datetime
  end

  create_table "catalog_logs", :force => true do |t|
    t.column "user_id",        :integer
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "action",         :string
    t.column "name",           :string
    t.column "comment",        :string
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  add_index "catalog_logs", ["user_id"], :name => "catalog_logs_user_id_index"
  add_index "catalog_logs", ["auditable_type", "auditable_id"], :name => "catalog_logs_auditable_type_index"
  add_index "catalog_logs", ["created_at"], :name => "catalog_logs_created_at_index"

  create_table "compound_results", :force => true do |t|
    t.column "row_no",                :integer,                :default => 0,  :null => false
    t.column "column_no",             :integer
    t.column "task_id",               :integer
    t.column "parameter_context_id",  :integer
    t.column "task_context_id",       :integer
    t.column "data_element_id",       :integer
    t.column "compound_parameter_id", :integer
    t.column "compound_id",           :integer
    t.column "compound_name",         :string
    t.column "protocol_version_id",   :integer
    t.column "label",                 :string
    t.column "row_label",             :string
    t.column "parameter_id",          :integer
    t.column "parameter_name",        :string,   :limit => 62
    t.column "data_value",            :float
    t.column "created_by",            :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",            :datetime,                               :null => false
    t.column "updated_by",            :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",            :datetime,                               :null => false
  end

  create_table "compounds", :force => true do |t|
    t.column "name",              :string,   :limit => 50, :default => "",    :null => false
    t.column "description",       :text
    t.column "formula",           :string,   :limit => 50
    t.column "mass",              :float
    t.column "smiles",            :string
    t.column "lock_version",      :integer,                :default => 0,     :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",        :datetime,                                  :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",        :datetime,                                  :null => false
    t.column "registration_date", :datetime
    t.column "iupacname",         :string,                 :default => ""
  end

  create_table "container_items", :force => true do |t|
    t.column "container_group_id", :integer,                 :null => false
    t.column "subject_type",       :string,  :default => "", :null => false
    t.column "subject_id",         :integer,                 :null => false
    t.column "slot_no",            :integer,                 :null => false
  end

  create_table "containers", :force => true do |t|
    t.column "name",            :string,   :limit => 128, :default => "", :null => false
    t.column "description",     :text
    t.column "plate_format_id", :integer
    t.column "lock_version",    :integer,                 :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",      :datetime,                                :null => false
    t.column "updated_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",      :datetime,                                :null => false
  end

  create_table "content_subjects", :force => true do |t|
    t.column "content_id",   :integer
    t.column "subject_type", :string
    t.column "subject_id",   :integer
  end

  create_table "contents", :force => true do |t|
    t.column "article_id",     :integer
    t.column "user_id",        :integer
    t.column "title",          :string
    t.column "permalink",      :string
    t.column "excerpt",        :text
    t.column "body",           :text
    t.column "excerpt_html",   :text
    t.column "body_html",      :text
    t.column "type",           :string,   :limit => 20
    t.column "author",         :string,   :limit => 100
    t.column "author_url",     :string
    t.column "author_email",   :string
    t.column "author_ip",      :string,   :limit => 100
    t.column "comments_count", :integer,                 :default => 0
    t.column "updater_id",     :integer
    t.column "version",        :integer
    t.column "project_id",     :integer
    t.column "approved",       :boolean,                 :default => false
    t.column "comment_age",    :integer,                 :default => 0
    t.column "filter",         :string
    t.column "user_agent",     :string
    t.column "referrer",       :string
    t.column "lock_version",   :integer,                 :default => 0,     :null => false
    t.column "created_by",     :string,   :limit => 32,  :default => "sys", :null => false
    t.column "created_at",     :datetime,                                   :null => false
    t.column "updated_by",     :string,   :limit => 32,  :default => "sys", :null => false
    t.column "updated_at",     :datetime,                                   :null => false
    t.column "published_at",   :datetime
    t.column "published_by",   :string
  end

  create_table "data_concepts", :force => true do |t|
    t.column "parent_id",         :integer
    t.column "name",              :string,   :limit => 50, :default => "",            :null => false
    t.column "data_context_id",   :integer,                :default => 1,             :null => false
    t.column "description",       :text
    t.column "access_control_id", :integer
    t.column "lock_version",      :integer,                :default => 0,             :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys",         :null => false
    t.column "created_at",        :datetime,                                          :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys",         :null => false
    t.column "updated_at",        :datetime,                                          :null => false
    t.column "type",              :string,                 :default => "DataConcept", :null => false
  end

  add_index "data_concepts", ["updated_by"], :name => "data_concepts_idx1"
  add_index "data_concepts", ["updated_at"], :name => "data_concepts_idx2"
  add_index "data_concepts", ["created_by"], :name => "data_concepts_idx3"
  add_index "data_concepts", ["created_at"], :name => "data_concepts_idx4"
  add_index "data_concepts", ["name"], :name => "data_concepts_name_idx"
  add_index "data_concepts", ["access_control_id"], :name => "data_concepts_acl_idx"
  add_index "data_concepts", ["data_context_id"], :name => "data_concepts_fk1"

  create_table "data_contexts", :force => true do |t|
    t.column "name",              :string,   :limit => 50, :default => "",    :null => false
    t.column "description",       :text
    t.column "access_control_id", :integer
    t.column "lock_version",      :integer,                :default => 0,     :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",        :datetime,                                  :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",        :datetime,                                  :null => false
  end

  add_index "data_contexts", ["updated_by"], :name => "data_contexts_idx1"
  add_index "data_contexts", ["updated_at"], :name => "data_contexts_idx2"
  add_index "data_contexts", ["created_by"], :name => "data_contexts_idx3"
  add_index "data_contexts", ["created_at"], :name => "data_contexts_idx4"
  add_index "data_contexts", ["name"], :name => "data_contexts_name_idx"
  add_index "data_contexts", ["access_control_id"], :name => "data_contexts_acl_idx"

  create_table "data_elements", :force => true do |t|
    t.column "name",              :string,   :limit => 50, :default => "",    :null => false
    t.column "description",       :text
    t.column "data_system_id",    :integer,                                   :null => false
    t.column "data_concept_id",   :integer,                                   :null => false
    t.column "access_control_id", :integer
    t.column "lock_version",      :integer,                :default => 0,     :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",        :datetime,                                  :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",        :datetime,                                  :null => false
    t.column "parent_id",         :integer,  :limit => 10
    t.column "style",             :string,   :limit => 10, :default => "",    :null => false
    t.column "content",           :text,                   :default => "",    :null => false
    t.column "estimated_count",   :integer
    t.column "type",              :string
  end

  add_index "data_elements", ["updated_by"], :name => "data_elements_idx1"
  add_index "data_elements", ["updated_at"], :name => "data_elements_idx2"
  add_index "data_elements", ["created_by"], :name => "data_elements_idx3"
  add_index "data_elements", ["created_at"], :name => "data_elements_idx4"
  add_index "data_elements", ["name"], :name => "data_elements_name_idx"
  add_index "data_elements", ["access_control_id"], :name => "data_elements_acl_idx"
  add_index "data_elements", ["data_concept_id"], :name => "data_element_fk2"
  add_index "data_elements", ["data_system_id"], :name => "data_element_fk1"

  create_table "data_environments", :force => true do |t|
    t.column "name",              :string,   :limit => 50, :default => "",    :null => false
    t.column "description",       :text
    t.column "data_context_id",   :integer,                :default => 1,     :null => false
    t.column "access_control_id", :integer
    t.column "lock_version",      :integer,                :default => 0,     :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",        :datetime,                                  :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",        :datetime,                                  :null => false
  end

  add_index "data_environments", ["updated_by"], :name => "data_environments_idx1"
  add_index "data_environments", ["updated_at"], :name => "data_environments_idx2"
  add_index "data_environments", ["created_by"], :name => "data_environments_idx3"
  add_index "data_environments", ["created_at"], :name => "data_environments_idx4"
  add_index "data_environments", ["name"], :name => "data_environments_name_idx"
  add_index "data_environments", ["access_control_id"], :name => "data_environments_acl_idx"
  add_index "data_environments", ["data_context_id"], :name => "data_environments_fk1"

  create_table "data_formats", :force => true do |t|
    t.column "name",          :string,   :limit => 128, :default => "", :null => false
    t.column "description",   :text
    t.column "default_value", :string
    t.column "format_regex",  :string
    t.column "lock_version",  :integer,                 :default => 0,  :null => false
    t.column "created_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",    :datetime,                                :null => false
    t.column "updated_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",    :datetime,                                :null => false
    t.column "data_type_id",  :integer
  end

  create_table "data_relations", :force => true do |t|
    t.column "from_concept_id", :integer, :limit => 32, :null => false
    t.column "to_concept_id",   :integer, :limit => 32, :null => false
    t.column "role_concept_id", :integer, :limit => 32, :null => false
  end

  add_index "data_relations", ["from_concept_id"], :name => "data_relations_from_idx"
  add_index "data_relations", ["to_concept_id"], :name => "data_relations_to_idx"
  add_index "data_relations", ["role_concept_id"], :name => "data_relations_role_idx"

  create_table "data_systems", :force => true do |t|
    t.column "name",              :string,   :limit => 50, :default => "",          :null => false
    t.column "description",       :text
    t.column "data_context_id",   :integer,                :default => 1,           :null => false
    t.column "access_control_id", :integer
    t.column "lock_version",      :integer,                :default => 0,           :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "sys",       :null => false
    t.column "created_at",        :datetime,                                        :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "sys",       :null => false
    t.column "updated_at",        :datetime,                                        :null => false
    t.column "adapter",           :string,   :limit => 50, :default => "mysql",     :null => false
    t.column "host",              :string,   :limit => 50, :default => "localhost"
    t.column "username",          :string,   :limit => 50, :default => "root"
    t.column "password",          :string,   :limit => 50, :default => ""
    t.column "database",          :string,   :limit => 50, :default => ""
    t.column "test_object",       :string,   :limit => 45, :default => "",          :null => false
  end

  add_index "data_systems", ["updated_by"], :name => "data_environments_idx1"
  add_index "data_systems", ["updated_at"], :name => "data_environments_idx2"
  add_index "data_systems", ["created_by"], :name => "data_environments_idx3"
  add_index "data_systems", ["created_at"], :name => "data_environments_idx4"
  add_index "data_systems", ["name"], :name => "data_environments_name_idx"
  add_index "data_systems", ["access_control_id"], :name => "data_environments_acl_idx"
  add_index "data_systems", ["data_context_id"], :name => "data_environments_fk1"

  create_table "data_types", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :string
    t.column "value_class",  :string
    t.column "lock_version", :integer,                :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",   :datetime,                               :null => false
    t.column "updated_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",   :datetime,                               :null => false
  end

  create_table "events", :force => true do |t|
    t.column "project_id",   :integer
    t.column "user_id",      :integer
    t.column "article_id",   :integer
    t.column "mode",         :string
    t.column "title",        :text
    t.column "body",         :text
    t.column "author",       :string,   :limit => 100
    t.column "comment_id",   :integer
    t.column "lock_version", :integer,                 :default => 0,     :null => false
    t.column "created_by",   :string,   :limit => 32,  :default => "sys", :null => false
    t.column "created_at",   :datetime,                                   :null => false
    t.column "updated_by",   :string,   :limit => 32,  :default => "sys", :null => false
    t.column "updated_at",   :datetime,                                   :null => false
  end

  create_table "experiment_logs", :force => true do |t|
    t.column "experiment_id",  :integer
    t.column "task_id",        :integer
    t.column "user_id",        :integer
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "action",         :string
    t.column "name",           :string
    t.column "comment",        :string
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  add_index "experiment_logs", ["experiment_id"], :name => "experiment_logs_experiment_id_index"
  add_index "experiment_logs", ["user_id"], :name => "experiment_logs_user_id_index"
  add_index "experiment_logs", ["auditable_type", "auditable_id"], :name => "experiment_logs_auditable_type_index"
  add_index "experiment_logs", ["created_at"], :name => "experiment_logs_created_at_index"

  create_table "experiment_statistics", :force => true do |t|
    t.column "experiment_id",      :integer
    t.column "study_parameter_id", :integer
    t.column "parameter_role_id",  :integer
    t.column "parameter_type_id",  :integer
    t.column "data_type_id",       :integer
    t.column "avg_values",         :float
    t.column "stddev_values",      :float
    t.column "num_values",         :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",         :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",         :float
    t.column "min_values",         :float
  end

  create_table "experiments", :force => true do |t|
    t.column "name",                :string,   :limit => 128, :default => "", :null => false
    t.column "description",         :text
    t.column "category_id",         :integer
    t.column "status_id",           :string
    t.column "study_id",            :integer
    t.column "protocol_version_id", :integer
    t.column "lock_version",        :integer,                 :default => 0,  :null => false
    t.column "created_by",          :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",          :datetime,                                :null => false
    t.column "updated_by",          :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",          :datetime,                                :null => false
    t.column "study_protocol_id",   :integer
  end

  create_table "identifiers", :force => true do |t|
    t.column "name",            :string
    t.column "prefix",          :string
    t.column "postfix",         :string
    t.column "mask",            :string
    t.column "current_counter", :integer,                :default => 0
    t.column "current_step",    :integer,                :default => 1
    t.column "lock_version",    :integer,                :default => 0,     :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",      :datetime,                                  :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",      :datetime,                                  :null => false
  end

  create_table "list_items", :force => true do |t|
    t.column "list_id",   :integer
    t.column "data_type", :string
    t.column "data_id",   :integer
    t.column "data_name", :string
  end

  create_table "lists", :force => true do |t|
    t.column "name",            :string
    t.column "description",     :text
    t.column "type",            :string
    t.column "expires_at",      :datetime
    t.column "lock_version",    :integer,                :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "data_element_id", :integer
  end

  create_table "logging_events", :force => true do |t|
    t.column "level",       :string
    t.column "source",      :string
    t.column "class_ref",   :string
    t.column "id_ref",      :string
    t.column "name",        :string
    t.column "description", :string
    t.column "comments",    :string
    t.column "data",        :text
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id",    :integer,                :default => 0,     :null => false
    t.column "project_id", :integer,                :default => 0,     :null => false
    t.column "role_id",    :integer,                :default => 0,     :null => false
    t.column "owner",      :boolean,                :default => false
    t.column "created_by", :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at", :datetime,                                  :null => false
    t.column "updated_by", :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at", :datetime,                                  :null => false
  end

  create_table "menu_items", :force => true do |t|
    t.column "parent_id",            :integer
    t.column "name",                 :string,  :default => "", :null => false
    t.column "label",                :string,  :default => "", :null => false
    t.column "seq",                  :integer
    t.column "controller_action_id", :integer
    t.column "content_page_id",      :integer
  end

  add_index "menu_items", ["controller_action_id"], :name => "fk_menu_item_controller_action_id"
  add_index "menu_items", ["content_page_id"], :name => "fk_menu_item_content_page_id"
  add_index "menu_items", ["parent_id"], :name => "fk_menu_item_parent_id"

  create_table "parameter_contexts", :force => true do |t|
    t.column "protocol_version_id", :integer
    t.column "parent_id",           :integer
    t.column "level_no",            :integer, :default => 0
    t.column "label",               :string
    t.column "default_count",       :integer, :default => 1
  end

  add_index "parameter_contexts", ["protocol_version_id"], :name => "parameter_contexts_process_instance_id_index"
  add_index "parameter_contexts", ["parent_id"], :name => "parameter_contexts_parent_id_index"
  add_index "parameter_contexts", ["label"], :name => "parameter_contexts_label_index"

  create_table "parameter_roles", :force => true do |t|
    t.column "name",         :string,   :limit => 50, :default => "", :null => false
    t.column "description",  :string,                 :default => "", :null => false
    t.column "weighing",     :integer,                :default => 0,  :null => false
    t.column "lock_version", :integer,                :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",   :datetime,                               :null => false
    t.column "updated_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",   :datetime,                               :null => false
  end

  create_table "parameter_types", :force => true do |t|
    t.column "name",            :string,   :limit => 50, :default => "", :null => false
    t.column "description",     :string,                 :default => "", :null => false
    t.column "weighing",        :integer,                :default => 0,  :null => false
    t.column "lock_version",    :integer,                :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "data_concept_id", :integer
    t.column "data_type_id",    :integer
    t.column "storage_unit",    :string
  end

  create_table "parameters", :force => true do |t|
    t.column "protocol_version_id",  :integer
    t.column "parameter_type_id",    :integer
    t.column "parameter_role_id",    :integer
    t.column "parameter_context_id", :integer
    t.column "column_no",            :integer
    t.column "sequence_num",         :integer
    t.column "name",                 :string,   :limit => 62
    t.column "description",          :string,   :limit => 62
    t.column "display_unit",         :string,   :limit => 20
    t.column "data_element_id",      :integer
    t.column "qualifier_style",      :string,   :limit => 1
    t.column "access_control_id",    :integer,                :default => 0,   :null => false
    t.column "lock_version",         :integer,                :default => 0,   :null => false
    t.column "created_by",           :string,   :limit => 32, :default => "",  :null => false
    t.column "created_at",           :datetime,                                :null => false
    t.column "updated_by",           :string,   :limit => 32, :default => "",  :null => false
    t.column "updated_at",           :datetime,                                :null => false
    t.column "mandatory",            :string,                 :default => "N"
    t.column "default_value",        :string
    t.column "data_type_id",         :integer
    t.column "data_format_id",       :integer
    t.column "study_parameter_id",   :integer
    t.column "study_queue_id",       :integer
  end

  add_index "parameters", ["name"], :name => "parameters_name_index"
  add_index "parameters", ["protocol_version_id"], :name => "parameters_process_instance_id_index"
  add_index "parameters", ["parameter_context_id"], :name => "parameters_parameter_context_id_index"
  add_index "parameters", ["parameter_type_id"], :name => "parameters_parameter_type_id_index"
  add_index "parameters", ["parameter_role_id"], :name => "parameters_parameter_role_id_index"
  add_index "parameters", ["updated_by"], :name => "parameters_updated_by_index"
  add_index "parameters", ["updated_at"], :name => "parameters_updated_at_index"

  create_table "permissions", :force => true do |t|
    t.column "checked", :boolean, :default => false, :null => false
    t.column "subject", :string,  :default => "",    :null => false
    t.column "action",  :string,  :default => "",    :null => false
  end

  create_table "plate_formats", :force => true do |t|
    t.column "name",         :string,   :limit => 128, :default => "", :null => false
    t.column "description",  :text
    t.column "rows",         :integer
    t.column "columns",      :integer
    t.column "lock_version", :integer,                 :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",   :datetime,                                :null => false
  end

  create_table "plate_wells", :force => true do |t|
    t.column "name",         :string,   :limit => 128, :default => "", :null => false
    t.column "label",        :string
    t.column "row_no",       :integer,                 :default => 0,  :null => false
    t.column "column_no",    :integer,                 :default => 0,  :null => false
    t.column "slot_no",      :integer,                 :default => 0,  :null => false
    t.column "lock_version", :integer,                 :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",   :datetime,                                :null => false
  end

  create_table "plates", :force => true do |t|
    t.column "name",           :string
    t.column "description",    :text
    t.column "external_ref",   :string
    t.column "quantity_unit",  :string
    t.column "quantity_value", :float
    t.column "url",            :string
    t.column "lock_version",   :integer,                :default => 0,     :null => false
    t.column "created_by",     :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",     :datetime,                                  :null => false
    t.column "updated_by",     :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",     :datetime,                                  :null => false
  end

  create_table "plugin_schema_info", :id => false, :force => true do |t|
    t.column "plugin_name", :string
    t.column "version",     :integer
  end

  create_table "process_definitions", :force => true do |t|
    t.column "name",              :string,   :limit => 30, :default => "", :null => false
    t.column "release",           :string,   :limit => 5,  :default => "", :null => false
    t.column "description",       :text
    t.column "protocol_catagory", :string,   :limit => 20
    t.column "protocol_status",   :string,   :limit => 20
    t.column "literature_ref",    :string
    t.column "access_control_id", :integer,                :default => 0,  :null => false
    t.column "lock_version",      :integer,                :default => 0,  :null => false
    t.column "created_by",        :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",        :datetime,                               :null => false
    t.column "updated_by",        :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",        :datetime,                               :null => false
  end

  add_index "process_definitions", ["name"], :name => "process_definitions_name_index"
  add_index "process_definitions", ["updated_by"], :name => "process_definitions_updated_by_index"
  add_index "process_definitions", ["updated_at"], :name => "process_definitions_updated_at_index"

  create_table "process_instances", :force => true do |t|
    t.column "process_definition_id", :integer,                              :null => false
    t.column "name",                  :string,  :limit => 77
    t.column "version",               :integer, :limit => 6,                 :null => false
    t.column "lock_version",          :integer,               :default => 0, :null => false
    t.column "created_by",            :string,  :limit => 32
    t.column "created_at",            :time
    t.column "updated_by",            :string,  :limit => 32
    t.column "updated_at",            :time
    t.column "how_to",                :text
  end

  add_index "process_instances", ["name"], :name => "process_instances_name_index"
  add_index "process_instances", ["process_definition_id"], :name => "process_instances_process_definition_id_index"
  add_index "process_instances", ["updated_by"], :name => "process_instances_updated_by_index"
  add_index "process_instances", ["updated_at"], :name => "process_instances_updated_at_index"

  create_table "process_statistics", :force => true do |t|
    t.column "study_parameter_id",  :integer
    t.column "protocol_version_id", :integer
    t.column "parameter_id",        :integer
    t.column "parameter_role_id",   :integer
    t.column "parameter_type_id",   :integer
    t.column "avg_values",          :float
    t.column "stddev_values",       :float
    t.column "num_values",          :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",          :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",          :float
    t.column "min_values",          :float
  end

  create_table "project_assets", :force => true do |t|
    t.column "project_id",       :integer
    t.column "parent_id",        :integer
    t.column "title",            :string
    t.column "content_type",     :string
    t.column "filename",         :string
    t.column "thumbnail",        :string
    t.column "size",             :integer
    t.column "width",            :integer
    t.column "height",           :integer
    t.column "thumbnails_count", :integer,                :default => 0
    t.column "published",        :boolean,                :default => false
    t.column "content_hash",     :string
    t.column "lock_version",     :integer,                :default => 0,     :null => false
    t.column "created_by",       :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",       :datetime,                                  :null => false
    t.column "updated_by",       :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",       :datetime,                                  :null => false
  end

  create_table "project_contents", :force => true do |t|
    t.column "project_id",     :integer,                                    :null => false
    t.column "type",           :string,   :limit => 20
    t.column "name",           :string
    t.column "title",          :string
    t.column "body",           :text
    t.column "body_html",      :text
    t.column "author_ip",      :string,   :limit => 100
    t.column "comments_count", :integer,                 :default => 0
    t.column "comment_age",    :integer,                 :default => 0
    t.column "published",      :boolean,                 :default => false
    t.column "content_hash",   :string
    t.column "lock_timeout",   :datetime
    t.column "lock_user_id",   :integer
    t.column "lock_version",   :integer,                 :default => 0,     :null => false
    t.column "created_by",     :string,   :limit => 32,  :default => "sys", :null => false
    t.column "created_at",     :datetime,                                   :null => false
    t.column "updated_by",     :string,   :limit => 32,  :default => "sys", :null => false
    t.column "updated_at",     :datetime,                                   :null => false
  end

  create_table "project_elements", :force => true do |t|
    t.column "parent_id",      :integer
    t.column "project_id",     :integer,                                              :null => false
    t.column "type",           :string,   :limit => 32, :default => "ProjectElement"
    t.column "position",       :integer,                :default => 1
    t.column "name",           :string,   :limit => 64, :default => "",               :null => false
    t.column "path",           :string,                 :default => "",               :null => false
    t.column "reference_id",   :integer
    t.column "reference_type", :string,   :limit => 20
    t.column "lock_version",   :integer,                :default => 0,                :null => false
    t.column "created_by",     :integer,                :default => 1,                :null => false
    t.column "created_at",     :datetime,                                             :null => false
    t.column "updated_by",     :integer,                :default => 1,                :null => false
    t.column "updated_at",     :datetime,                                             :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "name",               :string,   :limit => 30,  :default => "",    :null => false
    t.column "summary",            :text,                    :default => "",    :null => false
    t.column "status_id",          :integer,                 :default => 0,     :null => false
    t.column "title",              :string
    t.column "subtitle",           :string
    t.column "email",              :string
    t.column "ping_urls",          :text
    t.column "articles_per_page",  :integer,                 :default => 15
    t.column "host",               :string
    t.column "akismet_key",        :string,   :limit => 100
    t.column "akismet_url",        :string
    t.column "approve_comments",   :boolean
    t.column "comment_age",        :integer
    t.column "timezone",           :string
    t.column "filter",             :string
    t.column "permalink_style",    :string
    t.column "search_path",        :string
    t.column "tag_path",           :string
    t.column "search_layout",      :string
    t.column "tag_layout",         :string
    t.column "current_theme_path", :string
    t.column "created_by",         :string,   :limit => 32,  :default => "sys", :null => false
    t.column "created_at",         :datetime,                                   :null => false
    t.column "updated_by",         :string,   :limit => 32,  :default => "sys", :null => false
    t.column "updated_at",         :datetime,                                   :null => false
  end

  create_table "protocol_versions", :force => true do |t|
    t.column "study_protocol_id", :integer
    t.column "name",              :string,  :limit => 77
    t.column "version",           :integer, :limit => 6,                 :null => false
    t.column "lock_version",      :integer,               :default => 0, :null => false
    t.column "created_by",        :string,  :limit => 32
    t.column "created_at",        :time
    t.column "updated_by",        :string,  :limit => 32
    t.column "updated_at",        :time
    t.column "how_to",            :text
    t.column "report_id",         :integer
    t.column "analysis_id",       :integer
  end

  add_index "protocol_versions", ["name"], :name => "process_instances_name_index"
  add_index "protocol_versions", ["study_protocol_id"], :name => "process_instances_process_definition_id_index"
  add_index "protocol_versions", ["updated_by"], :name => "process_instances_updated_by_index"
  add_index "protocol_versions", ["updated_at"], :name => "process_instances_updated_at_index"

  create_table "queue_items", :force => true do |t|
    t.column "name",               :string
    t.column "comments",           :text
    t.column "study_queue_id",     :integer
    t.column "experiment_id",      :integer
    t.column "task_id",            :integer
    t.column "study_parameter_id", :integer
    t.column "data_type",          :string
    t.column "data_id",            :integer
    t.column "data_name",          :string
    t.column "requested_by",       :string,   :limit => 60
    t.column "assigned_to",        :string,   :limit => 60
    t.column "requested_for",      :datetime
    t.column "accepted_at",        :datetime
    t.column "completed_at",       :datetime
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_by",         :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_by",         :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "request_service_id", :integer
    t.column "status_id",          :integer
    t.column "priority_id",        :integer
  end

  create_table "report_columns", :force => true do |t|
    t.column "report_id",        :integer,                                   :null => false
    t.column "name",             :string,   :limit => 128, :default => "",   :null => false
    t.column "description",      :text
    t.column "join_model",       :string
    t.column "label",            :string
    t.column "action",           :text
    t.column "filter_operation", :string
    t.column "filter_text",      :string
    t.column "subject_type",     :string
    t.column "subject_id",       :integer
    t.column "data_element",     :integer
    t.column "is_visible",       :boolean,                 :default => true
    t.column "is_filterible",    :boolean,                 :default => true
    t.column "is_sortable",      :boolean,                 :default => true
    t.column "order_num",        :integer
    t.column "sort_num",         :integer
    t.column "sort_direction",   :string,   :limit => 11
    t.column "lock_version",     :integer,                 :default => 0,    :null => false
    t.column "created_by",       :string,   :limit => 32,  :default => "",   :null => false
    t.column "created_at",       :datetime,                                  :null => false
    t.column "updated_by",       :string,   :limit => 32,  :default => "",   :null => false
    t.column "updated_at",       :datetime,                                  :null => false
    t.column "join_name",        :string
  end

  create_table "reports", :force => true do |t|
    t.column "name",         :string,   :limit => 128, :default => "",       :null => false
    t.column "description",  :text
    t.column "base_model",   :string
    t.column "custom_sql",   :string
    t.column "lock_version", :integer,                 :default => 0,        :null => false
    t.column "created_by",   :string,   :limit => 32,  :default => "",       :null => false
    t.column "created_at",   :datetime,                                      :null => false
    t.column "updated_by",   :string,   :limit => 32,  :default => "",       :null => false
    t.column "updated_at",   :datetime,                                      :null => false
    t.column "type",         :string,                  :default => "Report"
  end

  create_table "repositories", :force => true do |t|
    t.column "name",        :string,   :limit => 30, :default => "",    :null => false
    t.column "description", :string,                 :default => "",    :null => false
    t.column "url",         :string,                 :default => "",    :null => false
    t.column "type",        :string,                 :default => "",    :null => false
    t.column "created_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",  :datetime,                                  :null => false
    t.column "updated_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",  :datetime,                                  :null => false
  end

  create_table "request_services", :force => true do |t|
    t.column "request_id",    :integer,                                 :null => false
    t.column "service_id",    :integer,                                 :null => false
    t.column "name",          :string,   :limit => 128, :default => "", :null => false
    t.column "description",   :text
    t.column "requested_by",  :string,   :limit => 60
    t.column "requested_for", :datetime
    t.column "assigned_to",   :string,   :limit => 60
    t.column "accepted_at",   :datetime
    t.column "completed_at",  :datetime
    t.column "lock_version",  :integer,                 :default => 0,  :null => false
    t.column "created_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",    :datetime,                                :null => false
    t.column "updated_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",    :datetime,                                :null => false
    t.column "status_id",     :integer
    t.column "priority_id",   :integer
  end

  create_table "requests", :force => true do |t|
    t.column "name",            :string,   :limit => 128, :default => "", :null => false
    t.column "description",     :text
    t.column "requested_by",    :string
    t.column "requested_for",   :string
    t.column "lock_version",    :integer,                 :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",      :datetime,                                :null => false
    t.column "updated_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",      :datetime,                                :null => false
    t.column "list_id",         :integer
    t.column "data_element_id", :integer
    t.column "status_id",       :integer
    t.column "priority_id",     :integer
  end

  create_table "role_permissions", :force => true do |t|
    t.column "role_id",       :integer,               :null => false
    t.column "subject",       :string,  :limit => 40
    t.column "action",        :string,  :limit => 40
    t.column "permission_id", :integer
  end

  add_index "role_permissions", ["role_id"], :name => "fk_roles_permission_role_id"

  create_table "roles", :force => true do |t|
    t.column "name",            :string,                    :default => "", :null => false
    t.column "parent_id",       :integer
    t.column "description",     :string,    :limit => 1024, :default => "", :null => false
    t.column "default_page_id", :integer
    t.column "cache",           :text
    t.column "created_at",      :timestamp
    t.column "updated_at",      :timestamp
  end

  add_index "roles", ["parent_id"], :name => "fk_role_parent_id"
  add_index "roles", ["default_page_id"], :name => "fk_role_default_page_id"

  create_table "samples", :force => true do |t|
  end

  create_table "sections", :force => true do |t|
    t.column "name",                :string
    t.column "show_paged_articles", :boolean,                :default => false
    t.column "articles_per_page",   :integer,                :default => 15
    t.column "layout",              :string
    t.column "template",            :string
    t.column "project_id",          :integer
    t.column "path",                :string
    t.column "articles_count",      :integer,                :default => 0
    t.column "archive_path",        :string
    t.column "archive_template",    :string
    t.column "position",            :integer,                :default => 1
    t.column "parent_id",           :integer
    t.column "desciption",          :text
    t.column "lock_version",        :integer,                :default => 0,     :null => false
    t.column "created_by",          :string,   :limit => 32, :default => "",    :null => false
    t.column "created_at",          :datetime,                                  :null => false
    t.column "updated_by",          :string,   :limit => 32, :default => "",    :null => false
    t.column "updated_at",          :datetime,                                  :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string,    :default => "", :null => false
    t.column "data",       :text
    t.column "created_at", :timestamp
    t.column "updated_at", :timestamp
  end

  create_table "specimens", :force => true do |t|
    t.column "name",             :string,   :limit => 128, :default => "", :null => false
    t.column "description",      :text
    t.column "weight",           :float
    t.column "sex",              :string
    t.column "birth",            :datetime
    t.column "age",              :datetime
    t.column "taxon_domain",     :string
    t.column "taxon_kingdom",    :string
    t.column "taxon_phylum",     :string
    t.column "taxon_class",      :string
    t.column "taxon_family",     :string
    t.column "taxon_order",      :string
    t.column "taxon_genus",      :string
    t.column "taxon_species",    :string
    t.column "taxon_subspecies", :string
    t.column "lock_version",     :integer,                 :default => 0,  :null => false
    t.column "created_by",       :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",       :datetime,                                :null => false
    t.column "updated_by",       :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",       :datetime,                                :null => false
  end

  create_table "studies", :force => true do |t|
    t.column "name",          :string,   :limit => 128, :default => "", :null => false
    t.column "description",   :text
    t.column "category_id",   :integer
    t.column "research_area", :string
    t.column "purpose",       :string
    t.column "lock_version",  :integer,                 :default => 0,  :null => false
    t.column "created_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",    :datetime,                                :null => false
    t.column "updated_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",    :datetime,                                :null => false
  end

  add_index "studies", ["name"], :name => "studies_name_index"
  add_index "studies", ["updated_by"], :name => "studies_updated_by_index"
  add_index "studies", ["updated_at"], :name => "studies_updated_at_index"

  create_table "study_logs", :force => true do |t|
    t.column "study_id",       :integer
    t.column "user_id",        :integer
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "action",         :string
    t.column "name",           :string
    t.column "comment",        :string
    t.column "changes",        :text
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  add_index "study_logs", ["study_id"], :name => "study_logs_study_id_index"
  add_index "study_logs", ["user_id"], :name => "study_logs_user_id_index"
  add_index "study_logs", ["auditable_type", "auditable_id"], :name => "study_logs_auditable_type_index"
  add_index "study_logs", ["created_at"], :name => "study_logs_created_at_index"

  create_table "study_parameters", :force => true do |t|
    t.column "parameter_type_id", :integer
    t.column "parameter_role_id", :integer
    t.column "study_id",          :integer,                 :default => 1
    t.column "name",              :string
    t.column "default_value",     :string
    t.column "data_element_id",   :integer
    t.column "data_type_id",      :integer
    t.column "data_format_id",    :integer
    t.column "description",       :string,  :limit => 1024, :default => "", :null => false
    t.column "display_unit",      :string
  end

  add_index "study_parameters", ["study_id"], :name => "study_parameters_study_id_index"
  add_index "study_parameters", ["name"], :name => "study_parameters_default_name_index"
  add_index "study_parameters", ["parameter_type_id"], :name => "study_parameters_parameter_type_id_index"
  add_index "study_parameters", ["parameter_role_id"], :name => "study_parameters_parameter_role_id_index"

  create_table "study_protocols", :force => true do |t|
    t.column "study_id",              :integer,                                      :null => false
    t.column "study_stage_id",        :integer,                 :default => 1,       :null => false
    t.column "current_process_id",    :integer
    t.column "process_definition_id", :integer
    t.column "process_style",         :string,   :limit => 128, :default => "Entry", :null => false
    t.column "name",                  :string,   :limit => 128, :default => "",      :null => false
    t.column "description",           :text
    t.column "literature_ref",        :text
    t.column "protocol_catagory",     :string,   :limit => 20
    t.column "protocol_status",       :string,   :limit => 20
    t.column "lock_version",          :integer,                 :default => 0,       :null => false
    t.column "created_by",            :string,   :limit => 32,  :default => "",      :null => false
    t.column "created_at",            :datetime,                                     :null => false
    t.column "updated_by",            :string,   :limit => 32,  :default => "",      :null => false
    t.column "updated_at",            :datetime,                                     :null => false
  end

  add_index "study_protocols", ["study_id"], :name => "study_protocols_study_id_index"
  add_index "study_protocols", ["current_process_id"], :name => "study_protocols_process_instance_id_index"
  add_index "study_protocols", ["process_definition_id"], :name => "study_protocols_process_definition_id_index"

  create_table "study_queues", :force => true do |t|
    t.column "name",               :string,   :limit => 128, :default => "",       :null => false
    t.column "description",        :text
    t.column "study_id",           :integer
    t.column "study_stage_id",     :integer
    t.column "study_parameter_id", :integer
    t.column "study_protocol_id",  :integer
    t.column "assigned_to",        :string,   :limit => 60
    t.column "status",             :string,                  :default => "new",    :null => false
    t.column "priority",           :string,                  :default => "normal", :null => false
    t.column "lock_version",       :integer,                 :default => 0,        :null => false
    t.column "created_by",         :string,   :limit => 32,  :default => "",       :null => false
    t.column "created_at",         :datetime,                                      :null => false
    t.column "updated_by",         :string,   :limit => 32,  :default => "",       :null => false
    t.column "updated_at",         :datetime,                                      :null => false
  end

  create_table "study_stages", :force => true do |t|
    t.column "name",         :string,   :limit => 128, :default => "", :null => false
    t.column "description",  :text
    t.column "lock_version", :integer,                 :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_by",   :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",   :datetime,                                :null => false
  end

  create_table "study_statistics", :force => true do |t|
    t.column "study_id",          :integer
    t.column "parameter_role_id", :integer
    t.column "parameter_type_id", :integer
    t.column "data_type_id",      :integer
    t.column "avg_values",        :float
    t.column "stddev_values",     :float
    t.column "num_values",        :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",        :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",        :float
    t.column "min_values",        :float
  end

  create_table "subscribers", :force => true do |t|
    t.column "user_id",    :integer, :default => 0, :null => false
    t.column "project_id", :integer, :default => 0, :null => false
  end

  create_table "system_settings", :force => true do |t|
    t.column "name",        :string,   :limit => 30, :default => "",    :null => false
    t.column "description", :string,                 :default => "",    :null => false
    t.column "text",        :string,                 :default => "0",   :null => false
    t.column "created_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",  :datetime,                                  :null => false
    t.column "updated_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",  :datetime,                                  :null => false
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "task_contexts", :force => true do |t|
    t.column "task_id",              :integer
    t.column "parameter_context_id", :integer
    t.column "label",                :string
    t.column "is_valid",             :boolean
    t.column "row_no",               :integer, :null => false
    t.column "parent_id",            :integer
    t.column "sequence_no",          :integer, :null => false
  end

  add_index "task_contexts", ["task_id"], :name => "task_contexts_task_id_index"
  add_index "task_contexts", ["parameter_context_id"], :name => "task_contexts_parameter_context_id_index"
  add_index "task_contexts", ["row_no"], :name => "task_contexts_row_no_index"
  add_index "task_contexts", ["label"], :name => "task_contexts_label_index"

  create_table "task_files", :force => true do |t|
    t.column "task_context_id", :integer
    t.column "parameter_id",    :integer
    t.column "data_uri",        :string
    t.column "is_external",     :boolean
    t.column "mime_type",       :string,   :limit => 250
    t.column "data_binary",     :text
    t.column "lock_version",    :integer,                 :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",      :datetime,                                :null => false
    t.column "updated_by",      :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",      :datetime,                                :null => false
    t.column "task_id",         :integer
    t.column "content_type",    :string
    t.column "parent_id",       :integer
    t.column "filename",        :string
    t.column "thumbnail",       :string
    t.column "size",            :integer
    t.column "width",           :integer
    t.column "height",          :integer
  end

  create_table "task_references", :force => true do |t|
    t.column "task_context_id", :integer
    t.column "parameter_id",    :integer
    t.column "data_element_id", :integer
    t.column "data_type",       :string
    t.column "data_id",         :integer
    t.column "data_name",       :string
    t.column "lock_version",    :integer,                :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "task_id",         :integer
  end

  add_index "task_references", ["task_id"], :name => "task_references_task_id_index"
  add_index "task_references", ["task_context_id"], :name => "task_references_task_context_id_index"
  add_index "task_references", ["parameter_id"], :name => "task_references_parameter_id_index"
  add_index "task_references", ["updated_at"], :name => "task_references_updated_at_index"
  add_index "task_references", ["updated_by"], :name => "task_references_updated_by_index"

  create_table "task_relations", :force => true do |t|
    t.column "to_task_id",   :integer
    t.column "from_task_id", :integer
    t.column "relation_id",  :integer
  end

  create_table "task_result_texts", :force => true do |t|
    t.column "row_no",                 :integer,                :default => 0,  :null => false
    t.column "column_no",              :integer
    t.column "task_id",                :integer
    t.column "parameter_context_id",   :integer
    t.column "task_context_id",        :integer
    t.column "reference_parameter_id", :integer
    t.column "data_element_id",        :integer
    t.column "data_type",              :string
    t.column "data_id",                :integer
    t.column "subject",                :string
    t.column "parameter_id",           :integer
    t.column "protocol_version_id",    :integer
    t.column "label",                  :string
    t.column "row_label",              :string
    t.column "parameter_name",         :string,   :limit => 62
    t.column "data_value",             :text
    t.column "created_by",             :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",             :datetime,                               :null => false
    t.column "updated_by",             :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",             :datetime,                               :null => false
  end

  create_table "task_result_values", :force => true do |t|
    t.column "row_no",                 :integer,                :default => 0,  :null => false
    t.column "column_no",              :integer
    t.column "task_id",                :integer
    t.column "parameter_context_id",   :integer
    t.column "task_context_id",        :integer
    t.column "reference_parameter_id", :integer
    t.column "data_element_id",        :integer
    t.column "data_type",              :string
    t.column "data_id",                :integer
    t.column "subject",                :string
    t.column "parameter_id",           :integer
    t.column "protocol_version_id",    :integer
    t.column "label",                  :string
    t.column "row_label",              :string
    t.column "parameter_name",         :string,   :limit => 62
    t.column "data_value",             :float
    t.column "created_by",             :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",             :datetime,                               :null => false
    t.column "updated_by",             :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",             :datetime,                               :null => false
  end

  create_table "task_results", :force => true do |t|
    t.column "protocol_version_id",  :integer
    t.column "parameter_context_id", :integer,                :default => 0,  :null => false
    t.column "label",                :string
    t.column "row_label",            :string
    t.column "row_no",               :integer,                :default => 0,  :null => false
    t.column "column_no",            :integer
    t.column "task_id",              :integer
    t.column "parameter_id",         :integer
    t.column "parameter_name",       :string,   :limit => 62
    t.column "data_value",           :binary
    t.column "created_by",           :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",           :datetime,                               :null => false
    t.column "updated_by",           :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",           :datetime,                               :null => false
  end

  create_table "task_statistics", :force => true do |t|
    t.column "task_id",           :integer
    t.column "parameter_id",      :integer
    t.column "parameter_role_id", :integer
    t.column "parameter_type_id", :integer
    t.column "data_type_id",      :integer
    t.column "avg_values",        :float
    t.column "stddev_values",     :float
    t.column "num_values",        :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",        :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",        :binary
    t.column "min_values",        :binary
  end

  create_table "task_stats1", :id => false, :force => true do |t|
    t.column "task_id",           :integer
    t.column "parameter_role_id", :integer
    t.column "parameter_type_id", :integer
    t.column "data_type_id",      :integer
    t.column "avg_values",        :float
    t.column "stddev_values",     :float
    t.column "num_values",        :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",        :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",        :float
    t.column "min_values",        :float
  end

  create_table "task_stats2", :id => false, :force => true do |t|
    t.column "task_id",       :integer
    t.column "parameter_id",  :integer
    t.column "avg_values",    :float
    t.column "stddev_values", :float
    t.column "num_values",    :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",    :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",    :float
    t.column "min_values",    :float
  end

  create_table "task_texts", :force => true do |t|
    t.column "task_context_id", :integer
    t.column "parameter_id",    :integer
    t.column "markup_style_id", :integer
    t.column "data_content",    :text
    t.column "lock_version",    :integer,                :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "task_id",         :integer
  end

  add_index "task_texts", ["task_id"], :name => "task_texts_task_id_index"
  add_index "task_texts", ["task_context_id"], :name => "task_texts_task_context_id_index"
  add_index "task_texts", ["parameter_id"], :name => "task_texts_parameter_id_index"
  add_index "task_texts", ["updated_at"], :name => "task_texts_updated_at_index"
  add_index "task_texts", ["updated_by"], :name => "task_texts_updated_by_index"

  create_table "task_values", :force => true do |t|
    t.column "task_context_id", :integer
    t.column "parameter_id",    :integer
    t.column "data_value",      :float
    t.column "display_unit",    :string
    t.column "lock_version",    :integer,                :default => 0,  :null => false
    t.column "created_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_by",      :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "task_id",         :integer
    t.column "storage_unit",    :string
  end

  add_index "task_values", ["task_id"], :name => "task_values_task_id_index"
  add_index "task_values", ["task_context_id"], :name => "task_values_task_context_id_index"
  add_index "task_values", ["parameter_id"], :name => "task_values_parameter_id_index"
  add_index "task_values", ["updated_at"], :name => "task_values_updated_at_index"
  add_index "task_values", ["updated_by"], :name => "task_values_updated_by_index"

  create_table "tasks", :force => true do |t|
    t.column "name",                :string,   :limit => 128, :default => "", :null => false
    t.column "description",         :text
    t.column "experiment_id",       :integer
    t.column "protocol_version_id", :integer
    t.column "status_id",           :integer
    t.column "is_milestone",        :boolean
    t.column "assigned_to",         :string,   :limit => 60
    t.column "priority_id",         :integer
    t.column "start_date",          :datetime
    t.column "end_date",            :datetime
    t.column "expected_hours",      :float
    t.column "done_hours",          :float
    t.column "lock_version",        :integer,                 :default => 0,  :null => false
    t.column "created_by",          :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",          :datetime,                                :null => false
    t.column "updated_by",          :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",          :datetime,                                :null => false
    t.column "study_protocol_id",   :integer
  end

  add_index "tasks", ["name"], :name => "tasks_name_index"
  add_index "tasks", ["experiment_id"], :name => "tasks_experiment_id_index"
  add_index "tasks", ["protocol_version_id"], :name => "tasks_process_instance_id_index"
  add_index "tasks", ["study_protocol_id"], :name => "tasks_study_protocol_id_index"
  add_index "tasks", ["start_date"], :name => "tasks_start_date_index"
  add_index "tasks", ["end_date"], :name => "tasks_end_date_index"

  create_table "tmp_data", :force => true do |t|
  end

  create_table "treatment_groups", :force => true do |t|
    t.column "name",          :string,   :limit => 128, :default => "", :null => false
    t.column "description",   :text
    t.column "study_id",      :integer
    t.column "experiment_id", :integer
    t.column "lock_version",  :integer,                 :default => 0,  :null => false
    t.column "created_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "created_at",    :datetime,                                :null => false
    t.column "updated_by",    :string,   :limit => 32,  :default => "", :null => false
    t.column "updated_at",    :datetime,                                :null => false
  end

  create_table "treatment_items", :force => true do |t|
    t.column "treatment_group_id", :integer,                 :null => false
    t.column "subject_type",       :string,  :default => "", :null => false
    t.column "subject_id",         :integer,                 :null => false
    t.column "sequence_order",     :integer,                 :null => false
  end

  create_table "user_settings", :force => true do |t|
    t.column "name",        :string,   :limit => 30, :default => "",    :null => false
    t.column "description", :string,                 :default => "",    :null => false
    t.column "value",       :string,                 :default => "0",   :null => false
    t.column "created_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "created_at",  :datetime,                                  :null => false
    t.column "updated_by",  :string,   :limit => 32, :default => "sys", :null => false
    t.column "updated_at",  :datetime,                                  :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",             :string,                 :default => "",    :null => false
    t.column "password_hash",    :string,   :limit => 40
    t.column "role_id",          :integer
    t.column "password_salt",    :string
    t.column "fullname",         :string
    t.column "email",            :string
    t.column "login",            :string,   :limit => 40
    t.column "activation_code",  :string,   :limit => 40
    t.column "state_id",         :integer
    t.column "activated_at",     :datetime
    t.column "token",            :string
    t.column "token_expires_at", :datetime
    t.column "filter",           :string
    t.column "admin",            :boolean,                :default => false
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "deleted_at",       :datetime
  end

  add_index "users", ["role_id"], :name => "fk_user_role_id"

  create_table "work_status", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :string
    t.column "lock_version", :integer,                :default => 0,  :null => false
    t.column "created_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "created_at",   :datetime,                               :null => false
    t.column "updated_by",   :string,   :limit => 32, :default => "", :null => false
    t.column "updated_at",   :datetime,                               :null => false
  end

end
