# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 280) do

  create_table "analysis_methods", :force => true do |t|
    t.column "name",                :string,   :limit => 128, :default => "", :null => false
    t.column "description",         :text
    t.column "class_name",          :string,                  :default => "", :null => false
    t.column "protocol_version_id", :integer
    t.column "lock_version",        :integer,                 :default => 0,  :null => false
    t.column "created_at",          :datetime,                                :null => false
    t.column "updated_at",          :datetime,                                :null => false
    t.column "updated_by_user_id",  :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id",  :integer,                 :default => 1,  :null => false
  end

  create_table "analysis_settings", :force => true do |t|
    t.column "analysis_method_id", :integer
    t.column "name",               :string,   :limit => 62
    t.column "script_body",        :text
    t.column "options",            :text
    t.column "parameter_id",       :integer
    t.column "data_type_id",       :integer
    t.column "level_no",           :integer
    t.column "column_no",          :integer
    t.column "io_mode",            :integer
    t.column "mandatory",          :string,                 :default => "N"
    t.column "default_value",      :string
    t.column "created_at",         :datetime,                                :null => false
    t.column "updated_at",         :datetime,                                :null => false
    t.column "updated_by_user_id", :integer,                :default => 1,   :null => false
    t.column "created_by_user_id", :integer,                :default => 1,   :null => false
  end

  create_table "audits", :force => true do |t|
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "user_id",        :integer
    t.column "user_type",      :string
    t.column "session_id",     :string
    t.column "action",         :string
    t.column "changes",        :text
    t.column "created_at",     :datetime
  end

  add_index "audits", ["auditable_id", "auditable_type"], :name => "auditable_index"
  add_index "audits", ["user_id", "user_type"], :name => "user_index"
  add_index "audits", ["created_at"], :name => "audits_created_at_index"

  create_table "batches", :force => true do |t|
    t.column "compound_id",        :integer,  :default => 0, :null => false
    t.column "name",               :string
    t.column "description",        :text
    t.column "external_ref",       :string
    t.column "quantity_unit",      :string
    t.column "quantity_value",     :float
    t.column "url",                :string
    t.column "lock_version",       :integer,  :default => 0, :null => false
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  add_index "batches", ["compound_id"], :name => "batches_compound_fk"

  create_table "catalog_logs", :force => true do |t|
    t.column "user_id",        :integer
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "action",         :string
    t.column "name",           :string
    t.column "comments",       :string
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  add_index "catalog_logs", ["user_id"], :name => "catalog_logs_user_id_index"
  add_index "catalog_logs", ["auditable_type", "auditable_id"], :name => "catalog_logs_auditable_type_index"
  add_index "catalog_logs", ["created_at"], :name => "catalog_logs_created_at_index"

  create_table "compound_results", :force => true do |t|
    t.column "row_no",                :integer,                               :null => false
    t.column "column_no",             :integer
    t.column "task_id",               :integer
    t.column "parameter_context_id",  :integer
    t.column "task_context_id",       :integer
    t.column "data_element_id",       :integer
    t.column "compound_parameter_id", :integer
    t.column "compound_id",           :integer
    t.column "compound_name",         :string
    t.column "protocol_version_id",   :integer
    t.column "label",                 :string
    t.column "row_label",             :string
    t.column "parameter_id",          :integer
    t.column "parameter_name",        :string,   :limit => 62
    t.column "data_value",            :float
    t.column "created_by_user_id",    :integer,                :default => 1, :null => false
    t.column "created_at",            :datetime,                              :null => false
    t.column "updated_by_user_id",    :integer,                :default => 1, :null => false
    t.column "updated_at",            :datetime,                              :null => false
  end

  create_table "compounds", :force => true do |t|
    t.column "name",               :string,   :limit => 50, :default => "", :null => false
    t.column "description",        :text
    t.column "formula",            :string,   :limit => 50
    t.column "mass",               :float
    t.column "smiles",             :string
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "registration_date",  :datetime
    t.column "iupacname",          :string,                 :default => ""
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  create_table "container_items", :force => true do |t|
    t.column "container_group_id", :integer,                 :null => false
    t.column "subject_type",       :string,  :default => "", :null => false
    t.column "subject_id",         :integer,                 :null => false
    t.column "slot_no",            :integer,                 :null => false
  end

  create_table "containers", :force => true do |t|
    t.column "name",               :string,   :limit => 128, :default => "", :null => false
    t.column "description",        :text
    t.column "plate_format_id",    :integer
    t.column "lock_version",       :integer,                 :default => 0,  :null => false
    t.column "created_at",         :datetime,                                :null => false
    t.column "updated_at",         :datetime,                                :null => false
    t.column "updated_by_user_id", :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                 :default => 1,  :null => false
  end

  create_table "data_concepts", :force => true do |t|
    t.column "parent_id",          :integer
    t.column "name",               :string,   :limit => 50, :default => "",            :null => false
    t.column "data_context_id",    :integer,                :default => 0,             :null => false
    t.column "description",        :text
    t.column "access_control_id",  :integer
    t.column "lock_version",       :integer,                :default => 0,             :null => false
    t.column "created_at",         :datetime,                                          :null => false
    t.column "updated_at",         :datetime,                                          :null => false
    t.column "type",               :string,                 :default => "DataConcept", :null => false
    t.column "updated_by_user_id", :integer,                :default => 1,             :null => false
    t.column "created_by_user_id", :integer,                :default => 1,             :null => false
  end

  add_index "data_concepts", ["updated_at"], :name => "data_concepts_idx2"
  add_index "data_concepts", ["created_at"], :name => "data_concepts_idx4"
  add_index "data_concepts", ["name"], :name => "data_concepts_name_idx"
  add_index "data_concepts", ["access_control_id"], :name => "data_concepts_acl_idx"
  add_index "data_concepts", ["data_context_id"], :name => "data_concepts_fk1"

  create_table "data_elements", :force => true do |t|
    t.column "name",               :string,   :limit => 50, :default => "", :null => false
    t.column "description",        :text
    t.column "data_system_id",     :integer,                                :null => false
    t.column "data_concept_id",    :integer,                                :null => false
    t.column "access_control_id",  :integer
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "parent_id",          :integer,  :limit => 10
    t.column "style",              :string,   :limit => 10, :default => "", :null => false
    t.column "content",            :text,                   :default => "", :null => false
    t.column "estimated_count",    :integer
    t.column "type",               :string
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  add_index "data_elements", ["updated_at"], :name => "data_elements_idx2"
  add_index "data_elements", ["created_at"], :name => "data_elements_idx4"
  add_index "data_elements", ["name"], :name => "data_elements_name_idx"
  add_index "data_elements", ["access_control_id"], :name => "data_elements_acl_idx"
  add_index "data_elements", ["data_concept_id"], :name => "data_element_fk2"
  add_index "data_elements", ["data_system_id"], :name => "data_element_fk1"

  create_table "data_formats", :force => true do |t|
    t.column "name",               :string,   :limit => 128, :default => "", :null => false
    t.column "description",        :text
    t.column "default_value",      :string
    t.column "format_regex",       :string
    t.column "lock_version",       :integer,                 :default => 0,  :null => false
    t.column "created_at",         :datetime,                                :null => false
    t.column "updated_at",         :datetime,                                :null => false
    t.column "data_type_id",       :integer
    t.column "updated_by_user_id", :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                 :default => 1,  :null => false
    t.column "format_sprintf",     :string
  end

  create_table "data_relations", :force => true do |t|
    t.column "from_concept_id", :integer, :limit => 32, :null => false
    t.column "to_concept_id",   :integer, :limit => 32, :null => false
    t.column "role_concept_id", :integer, :limit => 32, :null => false
  end

  add_index "data_relations", ["from_concept_id"], :name => "data_relations_from_idx"
  add_index "data_relations", ["to_concept_id"], :name => "data_relations_to_idx"
  add_index "data_relations", ["role_concept_id"], :name => "data_relations_role_idx"

  create_table "data_systems", :force => true do |t|
    t.column "name",               :string,   :limit => 50, :default => "",          :null => false
    t.column "description",        :text
    t.column "data_context_id",    :integer,                :default => 1,           :null => false
    t.column "access_control_id",  :integer
    t.column "lock_version",       :integer,                :default => 0,           :null => false
    t.column "created_at",         :datetime,                                        :null => false
    t.column "updated_at",         :datetime,                                        :null => false
    t.column "adapter",            :string,   :limit => 50, :default => "mysql",     :null => false
    t.column "host",               :string,   :limit => 50, :default => "localhost"
    t.column "username",           :string,   :limit => 50, :default => "root"
    t.column "password",           :string,   :limit => 50, :default => ""
    t.column "database",           :string,   :limit => 50, :default => ""
    t.column "test_object",        :string,   :limit => 45, :default => "",          :null => false
    t.column "updated_by_user_id", :integer,                :default => 1,           :null => false
    t.column "created_by_user_id", :integer,                :default => 1,           :null => false
  end

  add_index "data_systems", ["updated_at"], :name => "data_environments_idx2"
  add_index "data_systems", ["created_at"], :name => "data_environments_idx4"
  add_index "data_systems", ["name"], :name => "data_environments_name_idx"
  add_index "data_systems", ["access_control_id"], :name => "data_environments_acl_idx"
  add_index "data_systems", ["data_context_id"], :name => "data_environments_fk1"

  create_table "data_types", :force => true do |t|
    t.column "name",               :string
    t.column "description",        :string
    t.column "value_class",        :string
    t.column "lock_version",       :integer,  :default => 0, :null => false
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  create_table "db_files", :force => true do |t|
    t.column "data", :binary
  end

  create_table "experiment_logs", :force => true do |t|
    t.column "experiment_id",  :integer
    t.column "task_id",        :integer
    t.column "user_id",        :integer
    t.column "auditable_id",   :integer
    t.column "auditable_type", :string
    t.column "action",         :string
    t.column "name",           :string
    t.column "comments",       :string
    t.column "created_by",     :string
    t.column "created_at",     :datetime
  end

  add_index "experiment_logs", ["experiment_id"], :name => "experiment_logs_experiment_id_index"
  add_index "experiment_logs", ["user_id"], :name => "experiment_logs_user_id_index"
  add_index "experiment_logs", ["auditable_type", "auditable_id"], :name => "experiment_logs_auditable_type_index"
  add_index "experiment_logs", ["created_at"], :name => "experiment_logs_created_at_index"

  create_table "experiment_statistics", :force => true do |t|
    t.column "experiment_id",      :integer,               :default => 0, :null => false
    t.column "study_parameter_id", :integer
    t.column "parameter_role_id",  :integer
    t.column "parameter_type_id",  :integer
    t.column "data_type_id",       :integer
    t.column "avg_values",         :float
    t.column "stddev_values",      :float
    t.column "num_values",         :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",         :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",         :float
    t.column "min_values",         :float
  end

  create_table "experiments", :force => true do |t|
    t.column "name",                :string,   :limit => 128, :default => "", :null => false
    t.column "description",         :text
    t.column "category_id",         :integer
    t.column "status_id",           :integer,                 :default => 0,  :null => false
    t.column "study_id",            :integer,                                 :null => false
    t.column "protocol_version_id", :integer
    t.column "lock_version",        :integer,                 :default => 0,  :null => false
    t.column "created_at",          :datetime,                                :null => false
    t.column "updated_at",          :datetime,                                :null => false
    t.column "study_protocol_id",   :integer,                                 :null => false
    t.column "project_id",          :integer,                                 :null => false
    t.column "updated_by_user_id",  :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id",  :integer,                 :default => 1,  :null => false
    t.column "started_at",          :datetime
    t.column "ended_at",            :datetime
    t.column "expected_at",         :datetime
  end

  create_table "identifiers", :force => true do |t|
    t.column "name",               :string
    t.column "prefix",             :string
    t.column "postfix",            :string
    t.column "mask",               :string
    t.column "current_counter",    :integer,  :default => 0
    t.column "current_step",       :integer,  :default => 1
    t.column "lock_version",       :integer,  :default => 0, :null => false
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  create_table "list_items", :force => true do |t|
    t.column "list_id",   :integer
    t.column "data_type", :string
    t.column "data_id",   :integer
    t.column "data_name", :string
  end

  create_table "lists", :force => true do |t|
    t.column "name",               :string
    t.column "description",        :text
    t.column "type",               :string
    t.column "expires_at",         :datetime
    t.column "lock_version",       :integer,  :default => 0, :null => false
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "data_element_id",    :integer
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id",            :integer,  :default => 0, :null => false
    t.column "project_id",         :integer,  :default => 0, :null => false
    t.column "role_id",            :integer,  :default => 0, :null => false
    t.column "is_owner",           :boolean
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  create_table "parameter_contexts", :force => true do |t|
    t.column "protocol_version_id", :integer
    t.column "parent_id",           :integer
    t.column "level_no",            :integer, :default => 0
    t.column "label",               :string
    t.column "default_count",       :integer, :default => 1
  end

  add_index "parameter_contexts", ["protocol_version_id"], :name => "parameter_contexts_process_instance_id_index"
  add_index "parameter_contexts", ["parent_id"], :name => "parameter_contexts_parent_id_index"
  add_index "parameter_contexts", ["label"], :name => "parameter_contexts_label_index"

  create_table "parameter_roles", :force => true do |t|
    t.column "name",               :string,   :limit => 50, :default => "", :null => false
    t.column "description",        :string,                 :default => "", :null => false
    t.column "weighing",           :integer,                :default => 0,  :null => false
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  create_table "parameter_types", :force => true do |t|
    t.column "name",               :string,   :limit => 50, :default => "", :null => false
    t.column "description",        :string,                 :default => "", :null => false
    t.column "weighing",           :integer,                :default => 0,  :null => false
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "data_concept_id",    :integer
    t.column "data_type_id",       :integer
    t.column "storage_unit",       :string
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  create_table "parameters", :force => true do |t|
    t.column "protocol_version_id",  :integer
    t.column "parameter_type_id",    :integer
    t.column "parameter_role_id",    :integer
    t.column "parameter_context_id", :integer
    t.column "column_no",            :integer
    t.column "sequence_num",         :integer
    t.column "name",                 :string,   :limit => 62
    t.column "description",          :string,   :limit => 62
    t.column "display_unit",         :string,   :limit => 20
    t.column "data_element_id",      :integer
    t.column "qualifier_style",      :string,   :limit => 1
    t.column "access_control_id",    :integer,                :default => 0,   :null => false
    t.column "lock_version",         :integer,                :default => 0,   :null => false
    t.column "created_at",           :datetime,                                :null => false
    t.column "updated_at",           :datetime,                                :null => false
    t.column "mandatory",            :string,                 :default => "N"
    t.column "default_value",        :string
    t.column "data_type_id",         :integer
    t.column "data_format_id",       :integer
    t.column "study_parameter_id",   :integer
    t.column "study_queue_id",       :integer
    t.column "updated_by_user_id",   :integer,                :default => 1,   :null => false
    t.column "created_by_user_id",   :integer,                :default => 1,   :null => false
  end

  add_index "parameters", ["name"], :name => "parameters_name_index"
  add_index "parameters", ["protocol_version_id"], :name => "parameters_process_instance_id_index"
  add_index "parameters", ["parameter_context_id"], :name => "parameters_parameter_context_id_index"
  add_index "parameters", ["parameter_type_id"], :name => "parameters_parameter_type_id_index"
  add_index "parameters", ["parameter_role_id"], :name => "parameters_parameter_role_id_index"
  add_index "parameters", ["updated_at"], :name => "parameters_updated_at_index"

  create_table "permissions", :force => true do |t|
    t.column "checked", :boolean, :default => false, :null => false
    t.column "subject", :string,  :default => "",    :null => false
    t.column "action",  :string,  :default => "",    :null => false
  end

  create_table "plate_formats", :force => true do |t|
    t.column "name",               :string,   :limit => 128, :default => "", :null => false
    t.column "description",        :text
    t.column "rows",               :integer
    t.column "columns",            :integer
    t.column "lock_version",       :integer,                 :default => 0,  :null => false
    t.column "created_at",         :datetime,                                :null => false
    t.column "updated_at",         :datetime,                                :null => false
    t.column "updated_by_user_id", :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                 :default => 1,  :null => false
  end

  create_table "plate_wells", :force => true do |t|
    t.column "name",               :string,   :limit => 128, :default => "", :null => false
    t.column "label",              :string
    t.column "row_no",             :integer,                 :default => 0,  :null => false
    t.column "column_no",          :integer,                 :default => 0,  :null => false
    t.column "slot_no",            :integer,                 :default => 0,  :null => false
    t.column "lock_version",       :integer,                 :default => 0,  :null => false
    t.column "created_at",         :datetime,                                :null => false
    t.column "updated_at",         :datetime,                                :null => false
    t.column "updated_by_user_id", :integer,                 :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                 :default => 1,  :null => false
  end

  create_table "plates", :force => true do |t|
    t.column "name",               :string
    t.column "description",        :text
    t.column "external_ref",       :string
    t.column "quantity_unit",      :string
    t.column "quantity_value",     :float
    t.column "url",                :string
    t.column "lock_version",       :integer,  :default => 0, :null => false
    t.column "created_at",         :datetime,                :null => false
    t.column "updated_at",         :datetime,                :null => false
    t.column "updated_by_user_id", :integer,  :default => 1, :null => false
    t.column "created_by_user_id", :integer,  :default => 1, :null => false
  end

  create_table "plugin_schema_info", :id => false, :force => true do |t|
    t.column "plugin_name", :string
    t.column "version",     :integer
  end

  create_table "process_definitions", :force => true do |t|
    t.column "name",               :string,   :limit => 30, :default => "", :null => false
    t.column "release",            :string,   :limit => 5,  :default => "", :null => false
    t.column "description",        :text
    t.column "protocol_catagory",  :string,   :limit => 20
    t.column "protocol_status",    :string,   :limit => 20
    t.column "literature_ref",     :string
    t.column "access_control_id",  :integer,                :default => 0,  :null => false
    t.column "lock_version",       :integer,                :default => 0,  :null => false
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  add_index "process_definitions", ["name"], :name => "process_definitions_name_index"
  add_index "process_definitions", ["updated_at"], :name => "process_definitions_updated_at_index"

  create_table "process_instances", :force => true do |t|
    t.column "process_definition_id", :integer,                              :null => false
    t.column "name",                  :string,  :limit => 77
    t.column "version",               :integer, :limit => 6,                 :null => false
    t.column "lock_version",          :integer,               :default => 0, :null => false
    t.column "created_at",            :time
    t.column "updated_at",            :time
    t.column "how_to",                :text
    t.column "updated_by_user_id",    :integer,               :default => 1, :null => false
    t.column "created_by_user_id",    :integer,               :default => 1, :null => false
  end

  add_index "process_instances", ["name"], :name => "process_instances_name_index"
  add_index "process_instances", ["process_definition_id"], :name => "process_instances_process_definition_id_index"
  add_index "process_instances", ["updated_at"], :name => "process_instances_updated_at_index"

  create_table "process_statistics", :force => true do |t|
    t.column "study_parameter_id",  :integer
    t.column "protocol_version_id", :integer
    t.column "parameter_id",        :integer
    t.column "parameter_role_id",   :integer
    t.column "parameter_type_id",   :integer
    t.column "avg_values",          :float
    t.column "stddev_values",       :float
    t.column "num_values",          :integer, :limit => 20, :default => 0, :null => false
    t.column "num_unique",          :integer, :limit => 20, :default => 0, :null => false
    t.column "max_values",          :float
    t.column "min_values",          :float
  end

  create_table "project_assets", :force => true do |t|
    t.column "project_id",         :integer
    t.column "title",              :string
    t.column "parent_id",          :integer
    t.column "content_type",       :string
    t.column "filename",           :string
    t.column "thumbnail",          :string
    t.column "size",               :integer
    t.column "width",              :integer
    t.column "height",             :integer
    t.column "thumbnails_count",   :integer,  :default => 0
    t.column "published",          :boolean,  :default => false
    t.column "content_hash",       :string
    t.column "lock_version",       :integer,  :default => 0,     :null => false
    t.column "created_at",         :datetime,                    :null => false
    t.column "updated_at",         :datetime,                    :null => false
    t.column "updated_by_user_id", :integer,  :default => 1,     :null => false
    t.column "created_by_user_id", :integer,  :default => 1,     :null => false
    t.column "caption",            :text
    t.column "db_file_id",         :integer
  end

  create_table "project_contents", :force => true do |t|
    t.column "project_id",         :integer,                                    :null => false
    t.column "type",               :string,   :limit => 20
    t.column "name",               :string
    t.column "title",              :string
    t.column "body",               :text
    t.column "body_html",          :text
    t.column "author_ip",          :string,   :limit => 100
    t.column "comments_count",     :integer,                 :default => 0
    t.column "comment_age",        :integer,                 :default => 0
    t.column "published",          :boolean,                 :default => false
    t.column "content_hash",       :string
    t.column "lock_timeout",       :datetime
    t.column "lock_user_id",       :integer
    t.column "lock_version",       :integer,                 :default => 0,     :null => false
    t.column "created_at",         :datetime,                                   :null => false
    t.column "updated_at",         :datetime,                                   :null => false
    t.column "updated_by_user_id", :integer,                 :default => 1,     :null => false
    t.column "created_by_user_id", :integer,                 :default => 1,     :null => false
    t.column "left_limit",         :integer
    t.column "right_limit",        :integer
    t.column "parent_id",          :integer
  end

  create_table "project_elements", :force => true do |t|
    t.column "parent_id",              :integer
    t.column "project_id",             :integer,                                              :null => false
    t.column "type",                   :string,   :limit => 32, :default => "ProjectElement"
    t.column "position",               :integer,                :default => 1
    t.column "name",                   :string,   :limit => 64, :default => "",               :null => false
    t.column "reference_id",           :integer
    t.column "reference_type",         :string,   :limit => 20
    t.column "lock_version",           :integer,                :default => 0,                :null => false
    t.column "created_at",             :datetime,                                             :null => false
    t.column "updated_at",             :datetime,                                             :null => false
    t.column "updated_by_user_id",     :integer,                :default => 1,                :null => false
    t.column "created_by_user_id",     :integer,                :default => 1,                :null => false
    t.column "asset_id",               :integer
    t.column "content_id",             :integer
    t.column "published_hash",         :string
    t.column "project_elements_count", :integer,                :default => 0,                :null => false
    t.column "left_limit",             :integer,                :default => 0,                :null => false
    t.column "right_limit",            :integer,                :default => 0,                :null => false
  end

  add_index "project_elements", ["name", "parent_id"], :name => "parent_id", :unique => true
  add_index "project_elements", ["project_id"], :name => "project_id"
  add_index "project_elements", ["left_limit", "project_id"], :name => "left_limit"
  add_index "project_elements", ["right_limit", "project_id"], :name => "right_limit"

  create_table "projects", :force => true do |t|
    t.column "name",               :string,   :limit => 30, :default => "", :null => false
    t.column "summary",            :text,                   :default => "", :null => false
    t.column "status_id",          :integer,                :default => 0,  :null => false
    t.column "title",              :string
    t.column "email",              :string
    t.column "host",               :string
    t.column "comment_age",        :integer
    t.column "timezone",           :string
    t.column "created_at",         :datetime,                               :null => false
    t.column "updated_at",         :datetime,                               :null => false
    t.column "started_at",         :datetime
    t.column "ended_at",           :datetime
    t.column "expected_at",        :datetime
    t.column "done_hours",         :float
    t.column "expected_hours",     :float
    t.column "updated_by_user_id", :integer,                :default => 1,  :null => false
    t.column "created_by_user_id", :integer,                :default => 1,  :null => false
  end

  create_table "protocol_versions", :force => true do |t|
    t.column "study_protocol_id",  :integer
    t.column "name",               :string,  :limit => 77
    t.column "version",            :integer, :limit => 6,                 :null => false
    t.column "lock_version",       :integer,               :default => 0, :null => false
    t.column "created_at",         :time
    t.column "updated_at",         :time
    t.column "how_to",             :text
    t.column "report_id",          :integer
    t.column "analysis_id",        :integer
    t.column "updated_by_user_id", :integer,               :default => 1, :null => false
    t.column "created_by_user_id", :integer,               :default => 1, :null => false
  end

  add_index "protocol_versions", ["name"], :name => "process_instances_name_index"
  add_index "protocol_versions", ["study_protocol_id"], :name => "process_instances_process_definition_id_index"
  add_index "protocol_versions", ["updated_at"], :name => "process_instances_updated_at_index"

  create_table "queue_items", :force => true do |t|
    t.column "name",                 :string
    t.column "comments",             :text
    t.column "study_queue_id",       :integer
    t.column "experiment_id",        :integer
    t.column "task_id",              :integer
    t.column "study_parameter_id",   :integer
    t.column "data_type",            :string
    t.column "data_id",              :integer
    t.column "data_name",            :string
    t.column "expected_at",          :datetime
    t.column "started_at",           :datetime
    t.column "ended_at",             :datetime
    t.column "lock_version",         :integer,  :default => 0, :null => false
    t.column "created_at",           :datetime,                :null => false
    t.column "updated_at",           :datetime,                :null => false
    t.column "request_service_id",   :integer
    t.column "status_id",            :integer,  :default => 0, :null => false
    t.column "priority_id",          :integer
    t.column "updated_by_user_id",   :integer,  :default => 1, :null => false
    t.column "created_by_user_id",   :integer,  :default => 1, :null => false
    t.column "requested_by_user_id", :integer,  :default => 1
    t.column "assigned_to_user_id",  :integer,  :default => 1
  end

