class MembershipRemoveProjectId < ActiveRecord::Migration
  def self.up
    begin
       execute 'ALTER TABLE memberships DROP FOREIGN KEY memberships_fk3'
    rescue
    p 'there is a bug in some versions of mysql that means that if the foreign key does not exist, the error message generated by mysql is very confusing - in a mysql console'
    p 'SHOW CREATE TABLE memberships'
    p ' and check that memberships_fk3 has been deleted'
    end
       remove_column    :memberships, :project_id
  end
  
  def self.down
       add_column :memberships,:project_id,:integer
  end
end